---
# tasks file for limacharlie-sensor

- name: Install or upgrade deb
  import_tasks: install-deb.yml
  when: ansible_distribution in ['Debian', 'Ubuntu'] and
        ansible_architecture in ['i386', 'x86_64'] and
        #( ansible_facts.packages['limacharlie'] | map(attribute='version') | first | default('0') < version )
